### ISSUE TITLE
app does not run 

### ISSUE THREAD

**Issue by The-Code-Whisperer** [delivey/schoolvid19#2]
flask run

...\schoolvid19\app.py", line 44
    return redirect(f"/country/{country}")
                                        ^
SyntaxError: invalid syntax

**Comment by delivey** [comment]
hmmm, unsure of what could cause this since it works fine for me. I added a requirements.txt file, try using Flask 1.1.2 and see if it runs.

**Comment by abhishekshahane** [comment]
Go to the website mentioned I think. It works fine for me as well. Might be a requirements issue, so your safest bet is to go to the website.
